import Foundation

// Generated by gen-grammar.py; the lessons are authored there so cited verses get checked.
struct LessonExample: Codable, Hashable {
    let h: String        // pointed Hebrew
    let g: String        // gloss or reading
    var ref: String? = nil // "Jonah 1:3" when the example is in the bundled texts

    /// The deck view shows a lesson's examples as cards; an empty Strong's marks them unenrollable.
    var card: WordCard { WordCard(s: "", h: h, g: g, n: 0, root: [], conf: []) }
}

/// A small grid under the lesson text; the first column holds row labels.
struct LessonTable: Codable, Hashable {
    let title: String
    let columns: [String]
    let rows: [[String]]
}

struct Lesson: Codable, Identifiable, Hashable {
    let group: String
    let id: String
    let title: String
    let why: String      // one line: why this matters for reading
    let body: [String]   // paragraphs
    var tables: [LessonTable]? = nil
    let examples: [LessonExample]
}

struct GrammarGroup: Identifiable, Hashable {
    let id: String
    let title: String
    let glyph: String
}

/// The five groups on the dashboard, in teaching order. Ids match gen-grammar.py.
let grammarGroups: [GrammarGroup] = [
    GrammarGroup(id: "script", title: "Reading the script", glyph: "בַּת"),
    GrammarGroup(id: "attach", title: "Little words", glyph: "הַ"),
    GrammarGroup(id: "nouns", title: "Nouns and pronouns", glyph: "דָּבָר"),
    GrammarGroup(id: "verbs", title: "Verbs", glyph: "פָּעַל"),
    GrammarGroup(id: "sentences", title: "Sentences", glyph: "אֲשֶׁר"),
]

let lessons: [Lesson] = {
    let url = Bundle.main.url(forResource: "Grammar", withExtension: "json")!
    return try! JSONDecoder().decode([Lesson].self, from: Data(contentsOf: url))
}()

let lessonsByID = Dictionary(uniqueKeysWithValues: lessons.map { ($0.id, $0) })

func lessons(in group: GrammarGroup) -> [Lesson] { lessons.filter { $0.group == group.id } }

#if DEBUG
/// Smallest check that fails if a lesson lands in no group or has nothing to practise.
func grammarSelfCheck() {
    let groups = Set(grammarGroups.map(\.id))
    assert(lessonsByID.count == lessons.count, "duplicate lesson ids")
    for lesson in lessons {
        assert(groups.contains(lesson.group), "\(lesson.id) is in unknown group \(lesson.group)")
        assert(!lesson.examples.isEmpty, "\(lesson.id) has no examples")
        assert(!lesson.body.isEmpty, "\(lesson.id) has no body")
    }
}
#endif
