import Foundation

// Generated by gen-jonah.py from WLC/OSHB (CC BY 4.0) + WEB translation.
struct JonahWord: Codable {
    let h: String       // pointed Hebrew, cantillation stripped
    let g: String       // gloss
    var n: String? = nil // Assimil-style micro-note
}

struct JonahVerse: Codable, Identifiable {
    let c: Int
    let v: Int
    let en: String
    let words: [JonahWord]
    var id: String { "\(c):\(v)" }
    var ref: String { "Jonah \(c):\(v)" }
    var hebrew: String { words.map(\.h).joined(separator: " ") }
}

let jonahVerses: [JonahVerse] = {
    let url = Bundle.main.url(forResource: "Jonah", withExtension: "json")!
    return try! JSONDecoder().decode([JonahVerse].self, from: Data(contentsOf: url))
}()

/// Tapped words become SRS cards, keyed by pointed surface form.
func jonahCardID(_ w: JonahWord) -> String { "j-" + w.h }

let jonahCardsByID: [String: Card] = {
    var dict: [String: Card] = [:]
    for verse in jonahVerses {
        for w in verse.words where dict[jonahCardID(w)] == nil {
            dict[jonahCardID(w)] = Card(id: jonahCardID(w), hebrew: w.h, name: w.g, sound: "", kind: .word)
        }
    }
    return dict
}()
