import Foundation

// Generated by gen-text.py from OSHB/WLC (CC BY 4.0) + Strong's + the WEB translation.
struct VerseWord: Codable {
    let h: String        // pointed Hebrew, cantillation stripped
    let g: String        // gloss
    var n: String? = nil // Assimil-style micro-note
}

struct Verse: Codable, Identifiable {
    let c: Int
    let v: Int
    let en: String
    var zh: String? = nil // Union Version line; older Texts.json had none
    let words: [VerseWord]
    var book: String = "" // stamped in after decoding; the JSON groups verses under a book
    // `book` is absent from the JSON, so it must stay out of the decoder's required keys
    private enum CodingKeys: String, CodingKey { case c, v, en, zh, words }

    var id: String { "\(book) \(c):\(v)" }
    var ref: String { id }
    var hebrew: String { words.map(\.h).joined(separator: " ") }
    /// The translation in the chosen language.
    var text: String { Zh.on ? zh ?? en : en }
}

struct BookText: Identifiable, Codable {
    let name: String
    let heb: String
    let verses: [Verse]
    var id: String { name }
}

let books: [BookText] = {
    let url = Bundle.main.url(forResource: "Texts", withExtension: "json")!
    let raw = try! JSONDecoder().decode([BookText].self, from: Data(contentsOf: url))
    return raw.map { book in
        BookText(name: book.name, heb: book.heb, verses: book.verses.map {
            Verse(c: $0.c, v: $0.v, en: $0.en, zh: $0.zh, words: $0.words, book: book.name)
        })
    }
}()

func book(named name: String) -> BookText {
    books.first { $0.name == name } ?? books[0]
}

#if DEBUG
/// Smallest check that fails if a verse loses its book, which would send the
/// reader's pager to the wrong book and open it at the wrong verse.
func textsSelfCheck() {
    for book in books {
        assert(!book.verses.isEmpty, "\(book.name) has no verses")
        for (i, verse) in book.verses.enumerated() {
            assert(verse.book == book.name, "\(verse.id) is not stamped with \(book.name)")
            assert(Mikra.book(named: verse.book).verses.firstIndex { $0.id == verse.id } == i,
                   "\(verse.id) does not round-trip to index \(i)")
        }
    }
}
#endif
