import Foundation

// Generated by gen-text.py from OSHB/WLC (CC BY 4.0) + Strong's + the WEB translation.
struct VerseWord: Codable {
    let h: String        // pointed Hebrew, cantillation stripped
    let g: String        // gloss
    var n: String? = nil // Assimil-style micro-note
}

struct Verse: Codable, Identifiable {
    let c: Int
    let v: Int
    let en: String
    let words: [VerseWord]
    var book: String = "" // stamped in after decoding; the JSON groups verses under a book
    // `book` is absent from the JSON, so it must stay out of the decoder's required keys
    private enum CodingKeys: String, CodingKey { case c, v, en, words }

    var id: String { "\(book) \(c):\(v)" }
    var ref: String { id }
    var hebrew: String { words.map(\.h).joined(separator: " ") }
}

struct BookText: Identifiable, Codable {
    let name: String
    let heb: String
    let verses: [Verse]
    var id: String { name }
}

let books: [BookText] = {
    let url = Bundle.main.url(forResource: "Texts", withExtension: "json")!
    let raw = try! JSONDecoder().decode([BookText].self, from: Data(contentsOf: url))
    return raw.map { book in
        BookText(name: book.name, heb: book.heb, verses: book.verses.map {
            Verse(c: $0.c, v: $0.v, en: $0.en, words: $0.words, book: book.name)
        })
    }
}()

func book(named name: String) -> BookText {
    books.first { $0.name == name } ?? books[0]
}

/// Tapped words become SRS cards, keyed by pointed surface form.
/// The "j-" prefix predates the second book — it is kept so saved progress still resolves.
func verseWordCardID(_ w: VerseWord) -> String { "j-" + w.h }

let verseWordCardsByID: [String: Card] = {
    var dict: [String: Card] = [:]
    for book in books {
        for word in book.verses.flatMap(\.words) where dict[verseWordCardID(word)] == nil {
            dict[verseWordCardID(word)] = Card(id: verseWordCardID(word), hebrew: word.h,
                                               name: word.g, sound: "", kind: .word)
        }
    }
    return dict
}()
