import SwiftUI

// Generated by gen-words.py from OSHB/WLC (CC BY 4.0) + Strong's.
// The commonest content words in the Hebrew Bible — no particles, no names.
struct WordCard: Codable, Identifiable {
    let s: String       // Strong's number
    let h: String       // pointed dictionary form (verbs: 3ms perfect, as every lexicon lists them)
    let g: String       // gloss
    let n: Int          // occurrences in the Hebrew Bible
    let root: [String]  // same-root siblings, by Strong's number
    let conf: [String]  // look-alikes a beginner mixes up
    var p: String? = nil // part of speech (noun, verb, …); forms carry none
    var forms: [WordCard]? = nil // curated decks: every gender/number form of this meaning

    var id: String { "w-" + s }
    /// What "Learn this" enrols and the speaker reads: each form, or the word itself.
    var units: [WordCard] { forms ?? [self] }
}

let wordDeck: [WordCard] = {
    let url = Bundle.main.url(forResource: "Words", withExtension: "json")!
    return try! JSONDecoder().decode([WordCard].self, from: Data(contentsOf: url))
}()

let wordIndexByStrongs: [String: Int] =
    Dictionary(uniqueKeysWithValues: wordDeck.enumerated().map { ($1.s, $0) })

/// Bands of the deck in frequency order — five entry points into one continuous deck.
struct WordBand: Identifiable {
    let title: String
    let start: Int
    let count: Int
    let floor: Int // fewest occurrences of any word in the band
    var id: Int { start }
}

let wordBands: [WordBand] = {
    var start = 0
    return [("Core 100", 100), ("Next 100", 100), ("Third 100", 100), ("Next 200", 200), ("Next 500", 500)]
        .map { title, count in
            defer { start += count }
            return WordBand(title: title, start: start, count: count, floor: wordDeck[start + count - 1].n)
        }
}()

/// Curated decks (Pronouns, Numbers) from gen-words.py, shown with the same deck view as the bands.
struct Deck: Codable, Identifiable {
    let id: String
    let title: String
    let note: String
    let cards: [WordCard]
}

let decks: [Deck] = {
    let url = Bundle.main.url(forResource: "Decks", withExtension: "json")!
    return try! JSONDecoder().decode([Deck].self, from: Data(contentsOf: url))
}()

func deck(_ id: String) -> Deck { decks.first { $0.id == id }! }

/// One hue per vowel sound; the short vowel of a pair is dimmed (patach under qamats).
/// Sheva, dagesh, and the shin dots stay grey. Nil for anything that is not a mark.
func vowelColor(_ mark: Unicode.Scalar) -> Color? {
    let dim = 0.45
    // blue reads badly on a dark ground, so the e-vowels go yellow there
    let e = Color(UIColor { $0.userInterfaceStyle == .dark ? .systemYellow : .systemBlue })
    switch mark.value {
    case 0x05B8: return .red                       // qamats, a
    case 0x05B7, 0x05B2: return .red.opacity(dim)  // patach, hataf patach
    case 0x05B5: return e                          // tsere, e
    case 0x05B6, 0x05B1: return e.opacity(dim)     // segol, hataf segol
    case 0x05B4: return .green                     // hiriq, i
    case 0x05B9, 0x05BA: return .orange            // holam, o
    case 0x05B3: return .orange.opacity(dim)       // hataf qamats, short o
    case 0x05BB: return .purple.opacity(dim)       // qubuts, short u (shureq is fused into the vav)
    case 0x0591...0x05C7: return .gray             // sheva, dagesh, shin/sin dots, cantillation
    default: return nil
    }
}

/// The colour of the first vowel in a string, for the drawn vowel glyphs.
func vowelColor(in hebrew: String) -> Color {
    hebrew.unicodeScalars.first { (0x05B1...0x05BB).contains($0.value) }.flatMap(vowelColor) ?? .gray
}

/// Hebrew with each vowel point in its own colour, so the small marks stand out from the letters.
func pointed(_ hebrew: String) -> AttributedString {
    var out = AttributedString()
    for ch in hebrew {
        var run = AttributedString(String(ch.unicodeScalars.first!))
        for mark in ch.unicodeScalars.dropFirst() { // combining marks: niqqud, dagesh, shin dot
            // U+034F keeps iOS 26 from fusing letter and mark into one glyph that takes the letter's colour
            var m = AttributedString("\u{034F}" + String(mark))
            m.foregroundColor = vowelColor(mark)
            run += m
        }
        out += run
    }
    return out
}

/// Words whose gloss has a word starting with `query` ("go" finds "gods" and "go in", not "ago"),
/// in deck order so the commonest come first. A word in two decks appears once.
/// Chinese has no word boundaries, so a Chinese query matches anywhere in the Chinese gloss.
func searchWords(_ query: String) -> [WordCard] {
    let q = query.trimmingCharacters(in: .whitespaces)
    guard !q.isEmpty else { return [] }
    let chinese = q.unicodeScalars.contains { (0x4E00...0x9FFF).contains($0.value) }
    let pattern = "\\b" + NSRegularExpression.escapedPattern(for: q)
    var seen = Set<String>()
    return (wordDeck + decks.flatMap(\.cards)).filter {
        (chinese ? (Zh.strings[$0.g] ?? "").contains(q)
                 : $0.g.range(of: pattern, options: [.regularExpression, .caseInsensitive]) != nil)
            && seen.insert($0.id).inserted
    }
}

/// Deck words by id, for the custom sets, which store only ids.
let wordCardByID: [String: WordCard] = Dictionary(
    (wordDeck + decks.flatMap(\.cards)).map { ($0.id, $0) }, uniquingKeysWith: { a, _ in a })

#if DEBUG
/// Smallest check that fails if a band stops opening exactly its own cards, or a deck is empty.
func wordDeckSelfCheck() {
    assert(wordDeck.count == wordBands.reduce(0) { $0 + $1.count }, "bands don't cover the deck")
    for band in wordBands {
        let cards = WordDeckView.cards(for: band)
        assert(cards.map(\.s) == wordDeck[band.start ..< band.start + band.count].map(\.s),
               "\(band.title) opens the wrong cards")
    }
    assert(searchWords("say").first?.s == "559", "search misses 'to say'")
    assert(!searchWords("od").contains { $0.s == "430" }, "search matches mid-word")
    assert(searchWords("说").first?.s == "559", "Chinese search misses 'to say'")
    for d in decks {
        assert(!d.cards.isEmpty, "\(d.title) deck is empty")
        let ids = d.cards.flatMap(\.units).map(\.id)
        assert(Set(ids).count == ids.count, "\(d.title) has duplicate ids")
    }
}
#endif
