import Foundation

// Generated by gen-words.py from OSHB/WLC (CC BY 4.0) + Strong's.
// The commonest content words in the Hebrew Bible — no particles, no names.
struct WordCard: Codable, Identifiable {
    let s: String       // Strong's number
    let h: String       // pointed dictionary form (verbs: 3ms perfect, as every lexicon lists them)
    let g: String       // gloss
    let n: Int          // occurrences in the Hebrew Bible
    let root: [String]  // same-root siblings, by Strong's number
    let conf: [String]  // look-alikes a beginner mixes up

    var id: String { "w-" + s }
}

let wordDeck: [WordCard] = {
    let url = Bundle.main.url(forResource: "Words", withExtension: "json")!
    return try! JSONDecoder().decode([WordCard].self, from: Data(contentsOf: url))
}()

let wordIndexByStrongs: [String: Int] =
    Dictionary(uniqueKeysWithValues: wordDeck.enumerated().map { ($1.s, $0) })

/// Bands of 100 in frequency order. Three entry points into one continuous deck —
/// swiping past the end of a band carries on into the next.
struct WordBand: Identifiable {
    let title: String
    let start: Int
    let count: Int
    let floor: Int // fewest occurrences of any word in the band
    var id: Int { start }
}

let wordBandSize = 100

let wordBands: [WordBand] = stride(from: 0, to: wordDeck.count, by: wordBandSize).map { start in
    let end = min(start + wordBandSize, wordDeck.count)
    let names = ["Core 100", "Next 100", "Third 100"]
    return WordBand(title: start / wordBandSize < names.count ? names[start / wordBandSize]
                                                              : "Words \(start + 1)–\(end)",
                    start: start, count: end - start, floor: wordDeck[end - 1].n)
}

/// Deck words as SRS cards, for when "Learn this" enrolls one.
let wordCardsByID: [String: Card] = Dictionary(uniqueKeysWithValues: wordDeck.map {
    ($0.id, Card(id: $0.id, hebrew: $0.h, name: $0.g, sound: "", kind: .word))
})

/// Everything enrollable by hand: words tapped in the reader, and words taken from the deck.
let enrolledCardsByID = verseWordCardsByID.merging(wordCardsByID) { a, _ in a }

#if DEBUG
/// Smallest check that fails if a shuffled set stops covering exactly its band.
func wordDeckSelfCheck() {
    assert(wordDeck.count == wordBands.reduce(0) { $0 + $1.count }, "bands don't cover the deck")
    for band in wordBands {
        let order = WordDeckView.shuffledOrder(for: band)
        assert(order.count == band.count, "\(band.title) lost cards in the shuffle")
        assert(Set(order) == Set(band.start ..< band.start + band.count),
               "\(band.title) shuffled to the wrong cards")
    }
}
#endif
